### ISSUE TITLE
Add video/audio api

### ISSUE THREAD

**Issue by Kwerrell73** [Kwerrell73/mood-boost#1]
add free video/audio api to fetch

**Comment by vmcguire6377** [comment]
Added divs dinto the HTML with the api links for the video players for 3 relaxation videos. Added js to manage the functionality of the players themselves, and css for the descriptive text above each.

**Comment by vmcguire6377** [comment]
Pulled the latest changes from the develop branch into my feature/vmcguire branch. Re-tested browser functionality which was successful, and pushed up the code.
