### ISSUE TITLE
Styling - center response container and offset the breathe animation

### ISSUE THREAD

**Issue by Kwerrell73** [Kwerrell73/mood-boost#2]
center response container and offset the breathe animation

**Comment by Kwerrell73** [comment]
Also figure out how to have the gif replace itself, rather than add another

**Comment by umedcha** [comment]
Put some effort this morning to make adjustments to CSS file. Managed to move the breathe animation to the right side and center the response container.

**Comment by Kwerrell73** [comment]
Completed
